### ISSUE TITLE
Indicate in Readme how works liveReload.js

### ISSUE THREAD

**Issue by MaksZ** [FWeinb/metalsmith-watch#11]
Hello everyone,

First I thought that the metalsmith-watch injected automatically in the page the js code to make work liveReload. I think it would be nice to indicate in the Readme file to add this code in every page

`<script src="http://localhost:35729/livereload.js"></script>`

and install the liveReload chrome extension :
https://chrome.google.com/webstore/detail/livereload/jnihajbhpnppcggbcgedagnkighmdlei

Just to make it easier for beginners :)

**Comment by theqwertman** [comment]
The extension runs a websocket server that tells the page when to reload. Loading the Javascript file alone isn't the entire point, the JS file needs a livereload server (different than the file host server) to talk to.

**Comment by jme783** [comment]
+1, didn't realize that I needed to add the JS file to my template

**Comment by theqwertman** [comment]
If anyone has time, someone could update the documentation in a fork and do a pull request.

**Comment by jme783** [comment]
Done :) https://github.com/FWeinb/metalsmith-watch/pull/15

**Comment by FWeinb** [comment]
Thanks for the PR.
