### ISSUE TITLE
Rebuild not starts if changes were done in included template file

### ISSUE THREAD

**Issue by stunpix** [FWeinb/metalsmith-watch#13]
If template has kind of "include/extends" directive, then watcher detects changes in included/extended file, but it doesn't make a rebuild. Example:

**index.jade:**
```jade
extends _base.jade

block someSpecificContent
	div Some specific content
```

**_base.jade:**
```jade
doctype html
html
	head
		title Any title
		script(src='http://localhost:35729/livereload.js')
	body
		block someSpecificContent
```

Run `node build.js`. Now modify `index.jade`, plugin detects changes, rebuilds and notifies browser. This is OK.

Then modify `_base.jade` –  plugin detects changes, but no rebuild/notification happens. This is NOT OK.

**Comment by blunckr** [comment]
I have the same problem with scss files that import other files. Changes to the base file trigger a reload, changes to included files are logged, but do not trigger a reload

**Comment by chinedufn** [comment]
This is the current expected behavior. 

@blunckr The rebuilder function only runs changed source directory files through metalsmith's build change. https://github.com/FWeinb/metalsmith-watch/blob/master/lib/index.js#L29 . Your main .scss file isn't getting rebuilt with your new partial.

Ideally, metalsmith-watch would let you specify multiple mappings of source glob patterns patterns to rebuild glob patterns, similar to gulp.watch.
For example, whenever '../templates/partials/*' was changed '**/*.md' might be rebuilt.

The simplest fix for now though might be an optional flag to rebuild all files upon any change.

If @FWeinb wants to weigh in here, I wouldn't mind making a PR on the simpler (temporary?) fix.

**Comment by MoOx** [comment]
Interested for that too.
webpack as an API to tell him which files depends on what.
We might want to do the same, or at least offer an option to get full reload, better than nothing.

**Comment by MoOx** [comment]
I got a simple idea to implement: what if we just add an map option to say what will rebuild what ?
Like this

```js
watch({
  rebuildMapping: {
    "src/templates/**/*": "src/*", // editing a templates will trigger rebuild for everything
    "src/css/**/*": "src/css/*" // editing any css will rebuild css entry points
  }
})
```

@FWeinb what do you think about that ? I am open to make a PR for this.

**Comment by FWeinb** [comment]
@MoOx I like that. Would like your PR. I don't have much time to work on this.

**Comment by zenorocha** [comment]
+1

**Comment by MoOx** [comment]
@FWeinb I have made an entire rewrite of this plugin you can see here https://github.com/putaindecode/putaindecode.fr/blob/4a99b6194412b5f15ae941780fa3cde9ccc22557/scripts/metalsmith/server/watcher.es ( + decoupled lr https://github.com/putaindecode/putaindecode.fr/blob/4a99b6194412b5f15ae941780fa3cde9ccc22557/scripts/metalsmith/server/livereload.es)
tests: https://github.com/putaindecode/putaindecode.fr/blob/4a99b6194412b5f15ae941780fa3cde9ccc22557/scripts/metalsmith/server/__tests__/watcher.es
It's written in es6/7 using babel cause I can't work in es5 anymore :)

Here is an example of the usage: https://github.com/putaindecode/putaindecode.fr/blob/4a99b6194412b5f15ae941780fa3cde9ccc22557/scripts/build.js#L141-L146

Also I included a fix to metalsmith-collections and a feature to clean js cache (I am using react as a template engine, so when I save the file, I need the node cache to be cleaned).

If I do a PR, this is likely to change a lot of things (the code just won't be the same). I can do that if you want. Or I can just create another metalsmith plugin. You tell me :)

**Comment by FWeinb** [comment]
This looks awesome. I don't have much time to maintain this plugin but I can give you commit rights on this repo and add you to the author list on npm so you could publish the updated plugin yourself. Would that be ok with you?

**Comment by MoOx** [comment]
yup.
My npm login is "moox" :)

**Comment by FWeinb** [comment]
Awesome. You can push to this repo now. Will add you to npm once I am at home.

**Comment by MoOx** [comment]
Cool, I will push things when I get some times too. Glad to be a collaborator :)

**Comment by zenorocha** [comment]
Nice initiative @FWeinb and thanks for maintaining this @MoOx!

**Comment by FWeinb** [comment]
@MoOx 
You can now publish to npm. But be sure to change the version number of this plugin according to semver.

**Comment by MoOx** [comment]
Don't worry, I am a semver fanboy ;)
I will probably release 1.0 after a last small enhancement to make.

**Comment by FWeinb** [comment]
:+1:

**Comment by MoOx** [comment]
I opened a PR for this https://github.com/FWeinb/metalsmith-watch/pull/19
I have 2 tiny things to handle before merging.
