### ISSUE TITLE
Watch fails with use of template + partials

### ISSUE THREAD

**Issue by sarahgp** [FWeinb/metalsmith-watch#14]
Full report in [metalsmith #105](https://github.com/segmentio/metalsmith/issues/105).

**Comment by tibotiber** [comment]
This issue comes from metalsmith-templates. It has been solved, PRed and merged. Simply upgrade metalsmith-templates to 0.6.1! :)

More details at https://github.com/segmentio/metalsmith-templates/pull/42.

**Comment by FWeinb** [comment]
I assume this can be closed than.

**Comment by sarahgp** [comment]
Woohoo!
