### ISSUE TITLE
Circle offTimes, bedTimes, and timeLimits had worked fine, but haven't been the last few weeks.

### ISSUE THREAD

**Issue by VinceAtCircle** [FWeinb/metalsmith-watch#33]
Noticed in GetConfig that the customers with the recent time related problems (times change) had unusual data representing the week day and weekend days. MAC 8c:e2:da:f0:36:79 week day data such as "21430" and week end data "5656" for profile New Nate. Note: also has dailyQuotas "on", yet the "T" variable is set to "0", with other categories are set to non-zero values. His Circle worked fine for almost a year until weeks ago when he got a new iPhone 7 and around FW 1.4 release.

Another customer's Circle was working fine and then a few weeks ago had problems with the offTimes. MAC ec:e2:da:f1:1c:21 had Nicolas profile with week days "12340" and weekends "5656", Pat profile with weekends "5656". They also have an iPhone 7 and around FW 1.4 rollout.

Normally, week days are "01234" and weekends are "56".

**Comment by MoOx** [comment]
This issue does not make sense at all here, so I guess you posted in the wrong repo.

**Comment by VinceAtCircle** [comment]
Yes, I did post it to the wrong repository.
