### ISSUE TITLE
Watch multiple directories

### ISSUE THREAD

**Issue by jocelynlecomte** [FWeinb/metalsmith-watch#4]
It would be nice to have the option to watch several directories. My use case: I want to watch my src directory *and* my templates directory. For now, I have to include my templates in my src only so they can be watched, and they end up in the build directory, which is messy.

**Comment by doingweb** [comment]
I just worked through what sounds like a similar issue, where template changes were noticed by `gulp.watch()`, but the Metalsmith rebuild didn't include them. In my case, [Swig](http://paularmstrong.github.io/swig/)'s cache was [preventing the template from being rebuilt](https://github.com/paularmstrong/swig/blob/a86b63d8f273bd4c55b3f5f07716442d3f55c7ab/lib/swig.js#L601). Doing a [`swig.invalidateCache()`](https://github.com/paularmstrong/swig/blob/a86b63d8f273bd4c55b3f5f07716442d3f55c7ab/lib/swig.js#L251) just before the Metalsmith build fixed it right up.

I'm also using Gulp with Gulpsmith and BrowserSync, and am finding it quite enjoyable. If anyone's still interested in an example gulpfile for this kind of build, [here is my latest](https://github.com/doingweb/chrisdoingweb.com/blob/552d65cfe372f849c2981c782ea51116635f560c/gulpfile.js). The relevant parts go something like this:

```js
gulp.task('build', function () {
  swig.invalidateCache();
  
  return gulp.src('src/content/**/*')
    .pipe(gulpsmith()
      .use(templates({
        engine: 'swig',
        directory: 'src/templates'
      })))
    .pipe(gulp.dest('dist'));
});

gulp.task('serve', ['build'], function () {
  browserSync({
    server: {
      baseDir: 'dist'
    }
  });

  gulp.watch('{src/content/**/*,src/templates/**/*}', function () {
    runSequence('build', browserSync.reload);
  });
});
```

**Comment by mdvorscak** [comment]
If you want to use browser-sync instead, it is possible without using gulp watch. You can instead use browser-sync's middleware option.

In your "main" metalsmith file (maybe index.js)
```js
var Metalsmith  = require('metalsmith');
var markdown    = require('metalsmith-markdown');
var templates   = require('metalsmith-templates');
var browserSync = require('browser-sync');

browserSync({
    server     : "build",
    files      : ["src/*.md", "templates/*.hbs"],
    middleware : function (req, res, next) {
        build(next);
    }
});

function build (callback) {
    Metalsmith(__dirname)
        .use(markdown())
        .use(templates('handlebars'))
        .destination('./build')
        .build(function (err) {
                   var message = err ? err : 'Build complete';
                   console.log(message);
                   callback();
               });
}
```
