### ISSUE TITLE
Error of open .DS_Store file on Mac

### ISSUE THREAD

**Issue by arielyang** [FWeinb/metalsmith-watch#7]
/Users/xxxxxx/.nvm/v0.10.26/lib/node_modules/metalsmith-watch/lib/index.js:51
            if ( err ) { throw err; }
                               ^
Error: ENOENT, open '/Users/xxxxxx/Documents/Projects/xxxxxx/docs-metalsmith/build/assets/img/.DS_Store'

**Comment by MoOx** [comment]
Can you provide more input on this ?
It seems nobody else complained about a similar issue.
Looks like it's related to your environment.

**Comment by arielyang** [comment]
I can not repo either.
